/*******************************************************************************************************
* @author Lev
* @date 2020
*
* @description Handler for Account_Summary__c trigger
*/
public with sharing class AccountSummaryTriggerHandler {
   /* public static void handleBeforeInsert(List<Account_Summary__c> triggerNew) {
        RMDService.recalcRmdAccountType(triggerNew, null, 'insert');
    }

    public static void handleBeforeUpdate(List<Account_Summary__c> triggerNew, Map<Id, Account_Summary__c> oldMap) {
        RMDService.recalcRmdAccountType(triggerNew, oldMap, 'update');
    }

    public static void handleBeforeDelete(List<Account_Summary__c> triggerOld) {
        RMDService.recalcRmdAccountType(triggerOld, null, 'delete');
    } */
}