public class PopSandboxOther {
    public static void PopSandboxOther(){
    
 integer mynum = 1;
        
/*        
  //  Add Pavithra to groups
  		String userId = '0050V000006Z94CQAS';
        ID[] Groupids     = new ID[]{'00Gd0000000GgMtEAK','00G0V000003QwGcUAK','00G0V000003trqhUAA','00G0V000003QypgUAC','00G0V000003QypeUAC','00G0V000003QypfUAC','00G0V000003QyphUAC','00G0V000003QypiUAC','00G0V000003QypjUAC','00Gd0000000GsgnEAC',
            '00G0V000003QypkUAC','00G0V000003QyplUAC','00G0V000003QypmUAC','00G0V000003QypnUAC','00G0V000003yhDPUAY','00G0V000003QyppUAC','00G0V000003QypqUAC','00G0V000003QyprUAC','00G0V000003ztKcUAI'};
                for ( ID stid:groupids) {              
                    GroupMember GM2 = new GroupMember(groupid=stid,UserOrGroupId=Userid);
                    insert GM2;
                }    
        
   // remove Spring CM intergration
   		delete [Select id from SpringCMEos__Environment__c];    
   		     
*/
    
}     
    
    }


/*
 Pavithra  userid  - 0050V000006Z94CQAS
Treasury	00Gd0000000GgMtEAK
Member Support & Services	00G0V000003QwGcUAK
Member Relations	00G0V000003trqhUAA
High Transaction Treasury	00G0V000003QypgUAC
Account Processor	00G0V000003QypeUAC
Executive Team	00G0V000003QypfUAC
Member Relations Approver	00G0V000003QyphUAC
Member Relations Associate	00G0V000003QypiUAC
Treasury Approver	00G0V000003QypjUAC
Treasury Associate	00Gd0000000GsgnEAC
Account Processor	00G0V000003QypkUAC
Executives Online Transactions	00G0V000003QyplUAC
High Transaction Treasury	00G0V000003QypmUAC
Member Relations Approver	00G0V000003QypnUAC
Member Relations Associate	00G0V000003yhDPUAY
Online Transactions	00G0V000003QyppUAC
Treasury Approver	00G0V000003QypqUAC
Treasury Associate Online Trans	00G0V000003QyprUAC
Online Transactions	00G0V000003ztKcUAI
*/